extends: airbnb-base
plugins:
  - import
env:
    mocha: true
    node: true
rules :
  no-console:
    - off
  no-unused-vars:
    - off
  camelcase:
    - off
  eqeqeq:
    - off
  no-underscore-dangle:
    - off
  no-extend-native:
    - off
  no-plusplus:
    - off
  max-len: ["warn", 160]
  indent: ["off"]
